create table NONCCDB_USER_DASHBOARD_CONFIG_DASHBOARD_CONFIG_LINK (
    USER_DASHBOARD_CONFIG_ID varchar(36) not null,
    DASHBOARD_CONFIG_ID varchar(36) not null,
    primary key (USER_DASHBOARD_CONFIG_ID, DASHBOARD_CONFIG_ID)
);
